### ISSUE TITLE
Decide the sitemap

### ISSUE THREAD

**Issue by scordle** [scordle/DEV-website#8]
Use lucidchart.com to produce a sitemap to include all pages

**Comment by HPhuye0578** [comment]
link to site map: https://www.lucidchart.com/invitations/accept/7c21ff10-d681-4687-b3b0-cf1335e80485

**Comment by scordle** [comment]
Issue closed

**Comment by HPhuye0578** [comment]
updated three Carousel texts.

**Comment by HPhuye0578** [comment]
added acm logo
