### ISSUE TITLE
Decide basic layout

### ISSUE THREAD

**Issue by scordle** [scordle/DEV-website#9]
Create a wireframe diagram (lucidchart.com) to be the template for all pages on the site.

**Comment by jbowma9798** [comment]
Any update on when we can see a site layout. Was needing to start a color template and css for the index. Let me know if your needing any help.

**Comment by kwu6703** [comment]
Here's the link: 
https://www.lucidchart.com/documents/edit/d5043393-86fc-425a-b059-123b41bc062e/0
Not sure about this, think we may need more discussion in class. If anyone have any idea, just throw in.

**Comment by kwu6703** [comment]
https://www.lucidchart.com/invitations/accept/573b249b-de07-4c52-8bf1-389e26dac90d

**Comment by HPhuye0578** [comment]
Updated there Carousel images
